app: example-python-http-api
service: example-python-http-api-service

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
